format_version: 10
pipelines:
 prometheus:
  tools-apply:
    group: tools
    materials:
      git-da613e5:
        git: https://github.com/raju-b70/tools-automation-practice.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - Ansible:
          fetch_materials: true
          environment_variables:
            env: dev
          approval:
            type: manual
          jobs:
            ansible:
              tasks:
                - exec: {command: ansible-playbook, arguments: [ "-i", "prometheus-internal.rajdevops.store,", "tools.yml", "-e", "tool_name=prometheus", "-e", "ansible_user=ec2-user", "-e", "ansible_password=DevOps321" ], run_if: passed
